// Code generated by v3/generator; DO NOT EDIT.
package global

import (
	"context"

	"github.com/exoscale/egoscale/v3/oapi"
	"github.com/exoscale/egoscale/v3/utils"

	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

type OperationIface interface {

   Get(ctx context.Context, id openapi_types.UUID) (*oapi.Operation, error)

}

type Operation struct {
	oapiClient *oapi.ClientWithResponses
}

func NewOperation(c *oapi.ClientWithResponses) OperationIface {
	return &Operation{c}
}

func (a *Operation) Get(ctx context.Context, id openapi_types.UUID) (*oapi.Operation, error) {
	resp, err := a.oapiClient.GetOperationWithResponse(ctx, id)
	if err != nil {
		return nil, err
	}

    err = utils.WriteTestdata(nil, resp.JSON200, resp.StatusCode())
	if err != nil {
		return nil, err
	}

	err = utils.ParseResponseError(resp.StatusCode(), resp.Body)
	if err != nil {
		return nil, err
	}

	return resp.JSON200, nil
}


type MockOperation struct {
     CallCount int
}

func NewMockOperation() *MockOperation {
	return &MockOperation{}
}

func (a *MockOperation) Get(ctx context.Context, id openapi_types.UUID) (*oapi.Operation, error) {
    a.CallCount++

	resp := struct {
		JSON200 *oapi.Operation
	}{}
    err := utils.GetTestCall(a.CallCount, &resp.JSON200)
	if err != nil {
		return nil, err
	}

	return resp.JSON200, nil
}

