// Code generated by v3/generator; DO NOT EDIT.
package global

import (
	"context"

	"github.com/exoscale/egoscale/v3/oapi"
	"github.com/exoscale/egoscale/v3/utils"
)

type Zones struct {
	oapiClient *oapi.ClientWithResponses
}

func NewZones(c *oapi.ClientWithResponses) *Zones {
	return &Zones{c}
}

func (a *Zones) List(ctx context.Context) ([]oapi.Zone, error) {
	resp, err := a.oapiClient.ListZonesWithResponse(ctx)
	if err != nil {
		return nil, err
	}

	err = utils.ParseResponseError(resp.StatusCode(), resp.Body)
	if err != nil {
		return nil, err
	}

	return *resp.JSON200.Zones, nil
}

