// Code generated by v3/generator; DO NOT EDIT.
package compute

import (
	"context"

	"github.com/exoscale/egoscale/v3/oapi"
	"github.com/exoscale/egoscale/v3/utils"

	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

type PrivateNetworksIface interface {

   List(ctx context.Context) ([]oapi.PrivateNetwork, error)

   Get(ctx context.Context, id openapi_types.UUID) (*oapi.PrivateNetwork, error)

   Create(ctx context.Context, body oapi.CreatePrivateNetworkJSONRequestBody) (*oapi.Operation, error)

   Update(ctx context.Context, id openapi_types.UUID, body oapi.UpdatePrivateNetworkJSONRequestBody) (*oapi.Operation, error)

   Delete(ctx context.Context, id openapi_types.UUID) (*oapi.Operation, error)

}

type PrivateNetworks struct {
	oapiClient *oapi.ClientWithResponses
}

func NewPrivateNetworks(c *oapi.ClientWithResponses) PrivateNetworksIface {
	return &PrivateNetworks{c}
}

func (a *PrivateNetworks) List(ctx context.Context) ([]oapi.PrivateNetwork, error) {
	resp, err := a.oapiClient.ListPrivateNetworksWithResponse(ctx)
	if err != nil {
		return nil, err
	}

    err = utils.WriteTestdata(nil, resp.JSON200, resp.StatusCode())
	if err != nil {
		return nil, err
	}

	err = utils.ParseResponseError(resp.StatusCode(), resp.Body)
	if err != nil {
		return nil, err
	}

	return *resp.JSON200.PrivateNetworks, nil
}

func (a *PrivateNetworks) Get(ctx context.Context, id openapi_types.UUID) (*oapi.PrivateNetwork, error) {
	resp, err := a.oapiClient.GetPrivateNetworkWithResponse(ctx, id)
	if err != nil {
		return nil, err
	}

    err = utils.WriteTestdata(nil, resp.JSON200, resp.StatusCode())
	if err != nil {
		return nil, err
	}

	err = utils.ParseResponseError(resp.StatusCode(), resp.Body)
	if err != nil {
		return nil, err
	}

	return resp.JSON200, nil
}

func (a *PrivateNetworks) Create(ctx context.Context, body oapi.CreatePrivateNetworkJSONRequestBody) (*oapi.Operation, error) {
	resp, err := a.oapiClient.CreatePrivateNetworkWithResponse(ctx, body)
	if err != nil {
		return nil, err
	}

    err = utils.WriteTestdata(nil, resp.JSON200, resp.StatusCode())
	if err != nil {
		return nil, err
	}

	err = utils.ParseResponseError(resp.StatusCode(), resp.Body)
	if err != nil {
		return nil, err
	}

	return resp.JSON200, nil
}

func (a *PrivateNetworks) Update(ctx context.Context, id openapi_types.UUID, body oapi.UpdatePrivateNetworkJSONRequestBody) (*oapi.Operation, error) {
	resp, err := a.oapiClient.UpdatePrivateNetworkWithResponse(ctx, id, body)
	if err != nil {
		return nil, err
	}

    err = utils.WriteTestdata(nil, resp.JSON200, resp.StatusCode())
	if err != nil {
		return nil, err
	}

	err = utils.ParseResponseError(resp.StatusCode(), resp.Body)
	if err != nil {
		return nil, err
	}

	return resp.JSON200, nil
}

func (a *PrivateNetworks) Delete(ctx context.Context, id openapi_types.UUID) (*oapi.Operation, error) {
	resp, err := a.oapiClient.DeletePrivateNetworkWithResponse(ctx, id)
	if err != nil {
		return nil, err
	}

    err = utils.WriteTestdata(nil, resp.JSON200, resp.StatusCode())
	if err != nil {
		return nil, err
	}

	err = utils.ParseResponseError(resp.StatusCode(), resp.Body)
	if err != nil {
		return nil, err
	}

	return resp.JSON200, nil
}


type MockPrivateNetworks struct {
     CallCount int
}

func NewMockPrivateNetworks() *MockPrivateNetworks {
	return &MockPrivateNetworks{}
}

func (a *MockPrivateNetworks) List(ctx context.Context) ([]oapi.PrivateNetwork, error) {
    a.CallCount++

	resp := struct {
		JSON200 struct {
			PrivateNetworks *[]oapi.PrivateNetwork
		}
	}{}
    err := utils.GetTestCall(a.CallCount, &resp.JSON200)
	if err != nil {
		return nil, err
	}

	return *resp.JSON200.PrivateNetworks, nil
}

func (a *MockPrivateNetworks) Get(ctx context.Context, id openapi_types.UUID) (*oapi.PrivateNetwork, error) {
    a.CallCount++

	resp := struct {
		JSON200 *oapi.PrivateNetwork
	}{}
    err := utils.GetTestCall(a.CallCount, &resp.JSON200)
	if err != nil {
		return nil, err
	}

	return resp.JSON200, nil
}

func (a *MockPrivateNetworks) Create(ctx context.Context, body oapi.CreatePrivateNetworkJSONRequestBody) (*oapi.Operation, error) {
    a.CallCount++

	resp := struct {
		JSON200 *oapi.Operation
	}{}
    err := utils.GetTestCall(a.CallCount, &resp.JSON200)
	if err != nil {
		return nil, err
	}

	return resp.JSON200, nil
}

func (a *MockPrivateNetworks) Update(ctx context.Context, id openapi_types.UUID, body oapi.UpdatePrivateNetworkJSONRequestBody) (*oapi.Operation, error) {
    a.CallCount++

	resp := struct {
		JSON200 *oapi.Operation
	}{}
    err := utils.GetTestCall(a.CallCount, &resp.JSON200)
	if err != nil {
		return nil, err
	}

	return resp.JSON200, nil
}

func (a *MockPrivateNetworks) Delete(ctx context.Context, id openapi_types.UUID) (*oapi.Operation, error) {
    a.CallCount++

	resp := struct {
		JSON200 *oapi.Operation
	}{}
    err := utils.GetTestCall(a.CallCount, &resp.JSON200)
	if err != nil {
		return nil, err
	}

	return resp.JSON200, nil
}

