// Package render turns ir declarations into formatted Go source.
package render

import (
	"bytes"
	"embed"
	"fmt"
	"go/format"
	"strings"
	"text/template"

	"github.com/exoscale/egoscale/v3/generator/ir"
)

//go:embed *.tmpl
var templatesFS embed.FS

var templates = template.Must(template.New("").Funcs(template.FuncMap{
	"formatQuery":   formatQuery,
	"findCondition": findCondition,
}).ParseFS(templatesFS, "*.tmpl"))

// Header is the comment of generated go source files.
const Header = `// Package %s provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/egoscale/v3/generator version v0.0.1 DO NOT EDIT.
`

// File renders a Go source file, formatted with gofmt.
func File(f ir.File) ([]byte, error) {
	src, err := Source(f)
	if err != nil {
		return nil, err
	}

	content, err := format.Source(src)
	if err != nil {
		return nil, fmt.Errorf("format.Source: %w", err)
	}

	return content, nil
}

// Source renders a Go source file, unformatted.
func Source(f ir.File) ([]byte, error) {
	var b bytes.Buffer
	fmt.Fprintf(&b, Header, f.Package)
	fmt.Fprintf(&b, "package %s\n\nimport (\n", f.Package)
	for _, i := range f.Imports {
		// An empty import separates groups.
		if i == "" {
			b.WriteString("\n")
			continue
		}
		fmt.Fprintf(&b, "\t%q\n", i)
	}
	b.WriteString(")\n\n")

	for _, d := range f.Decls {
		if err := Decl(&b, d); err != nil {
			return nil, err
		}
		b.WriteString("\n")
	}

	return b.Bytes(), nil
}

// Decl renders a declaration.
func Decl(b *bytes.Buffer, d ir.Decl) error {
	switch d := d.(type) {
	case ir.TypeDef:
		writeDoc(b, d.Doc)
		fmt.Fprintf(b, "type %s %s\n", d.Name, d.Type)
	case ir.Enum:
		writeDoc(b, d.Doc)
		fmt.Fprintf(b, "type %s %s\nconst (\n", d.Name, d.Base)
		for _, v := range d.Values {
			fmt.Fprintf(b, "%s %s = %s\n", v.Name, d.Name, v.Literal)
		}
		b.WriteString(")\n")
	case ir.Struct:
		writeDoc(b, d.Doc)
		fmt.Fprintf(b, "type %s struct {\n", d.Name)
		for _, f := range d.Fields {
			writeDoc(b, f.Doc)
			fmt.Fprintf(b, "%s %s %s\n", f.Name, f.Type, tag(f))
		}
		b.WriteString("}\n")
	case ir.Aliases:
		for _, a := range d.Aliases {
			fmt.Fprintf(b, "type %s = %s\n", a.Name, a.Target)
		}
	case ir.QueryOpts:
		return templates.ExecuteTemplate(b, "queryopts.tmpl", d)
	case ir.Findable:
		return templates.ExecuteTemplate(b, "findable.tmpl", d)
	case ir.Operation:
		return templates.ExecuteTemplate(b, "operation.tmpl", newOperationView(d))
	case ir.Client:
		return templates.ExecuteTemplate(b, "client.tmpl", d)
	default:
		return fmt.Errorf("render: unknown declaration %T", d)
	}

	return nil
}

func writeDoc(b *bytes.Buffer, doc string) {
	if doc != "" {
		b.WriteString(doc + "\n")
	}
}

func tag(f ir.Field) string {
	t := fmt.Sprintf("json:%q", f.JSON)
	if f.OmitEmpty {
		t = fmt.Sprintf(`json:"%s,omitempty"`, f.JSON)
	}
	if len(f.Validate) > 0 {
		t += fmt.Sprintf(` validate:"%s"`, strings.Join(f.Validate, ","))
	}

	return "`" + t + "`"
}

func formatQuery(o ir.QueryOpt) string {
	if o.ArgType == ir.Named("time.Time") {
		return o.Arg + ".Format(time.RFC3339)"
	}

	return "fmt.Sprint(" + o.Arg + ")"
}

func findCondition(f ir.Findable) string {
	conds := make([]string, 0, len(f.Fields))
	for _, field := range f.Fields {
		conds = append(conds, fmt.Sprintf("string(elem.%s) == %s", field, f.Param))
	}

	return strings.Join(conds, " || ")
}

// operationView adds the Go expressions derived from an ir.Operation to the operation template.
type operationView struct {
	ir.Operation
	Params       string
	Results      string
	PathExpr     string
	ErrReturn    string
	NewReturn    string
	ReturnTarget string
}

func newOperationView(op ir.Operation) operationView {
	v := operationView{Operation: op, Results: "error"}

	params := []string{"ctx context.Context"}
	for _, p := range op.Params {
		params = append(params, p.Name+" "+p.Type.String())
	}
	if op.Body != nil {
		params = append(params, "req "+op.Body.String())
	}
	if op.QueryOpts != "" {
		params = append(params, "opts ..."+op.QueryOpts)
	}
	v.Params = strings.Join(params, ", ")

	v.PathExpr = fmt.Sprintf("%q", op.Path)
	if len(op.PathArgs) > 0 {
		v.PathExpr = `fmt.Sprintf("` + op.Path + `", ` + strings.Join(op.PathArgs, ", ") + ")"
	}

	if op.Return != nil {
		v.Results = "(" + op.Return.String() + ", error)"
		v.ErrReturn = "nil, "
		switch r := op.Return.(type) {
		case ir.Pointer:
			v.NewReturn = "new(" + r.Elem.String() + ")"
			v.ReturnTarget = "bodyresp"
		default:
			v.NewReturn = r.String() + "{}"
			v.ReturnTarget = "&bodyresp"
		}
	}

	return v
}
