# .goreleaser.yml
# Build customization
builds:
  - main: ./cmd/cs/
    binary: cs
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
  - main: ./cmd/exo/
    binary: exo
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

sign:
  cmd: gpg
  args: ["-a", "-u", "ops@exoscale.ch", "--detach-sign", "${artifact}"]
  artifacts: all

archive:
  name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
