builds:
  - main: ./cmd/cs/
    binary: cs
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
      - openbsd
    goarch:
      - amd64
  - main: ./cmd/exo/
    binary: exo
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
      - openbsd
    goarch:
      - amd64

sign:
  cmd: gpg
  args: ["-u", "ops@exoscale.ch", "--detach-sign", "${artifact}"]
  artifacts: none

archive:
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE
    - CHANGELOG.md

release:
  github:
    owner: exoscale
    name: egoscale
  draft: true

nfpm:
  vendor: Exoscale
  homepage: https://www.exoscale.com/
  description: Tools to manage (almost) everything at Exoscale from the command line.
  license: Apache 2.0
  formats:
    - deb
    - rpm

brew:
  name: exo

  github:
    owner: pierre-emmanuelJ
    name: homebrew-tap

  # Git author used to commit to the repository.
  # Defaults are shown.
  commit_author:
    name: pierre-emmanuelJ
    email: pierre-emmanuel.jacquier@epitech.eu

  # Your app's homepage.
  # Default is empty.
  homepage: "https://github.com/exoscale/egoscale/tree/master/cmd/exo"

  # Your app's description.
  # Default is empty.
  description: "EXO Manage easily your Exoscale infrastructure from the exo command-line"

  # Setting this will prevent goreleaser to actually try to commit the updated
  # formula - instead, the formula file will be stored on the dist folder only,
  # leaving the responsibility of publishing it to the user.
  # Default is false.
  skip_upload: true

  # Custom install script for brew.
  # Default is 'bin.install "program"'.
  install: |
    bin.install "exo"