# .goreleaser.yml
# Build customization
builds:
  - main: ./cmd/cs/
    binary: cs
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
# Archive customization
archive:
  format: tar.gz
    