language: go

dist: trusty
sudo: required

go:
- 1.7.x
- 1.8.x
- 1.9.x
- 1.10.x
- 1.11.x

env:
  - DEP_VERSION=0.5.0 GORELEASER_VERSION=0.82.2 NFPM_VERSION=0.9.3 GOLANGCI_LINT_VERSION=1.10.2

cache: apt

addons:
  apt:
    update: true
    packages:
    - rpm

install: |
  curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin v${GOLANGCI_LINT_VERSION}
  curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  chmod +x $GOPATH/bin/dep
  wget https://github.com/goreleaser/goreleaser/releases/download/v${GORELEASER_VERSION}/goreleaser_amd64.deb
  sudo dpkg -i goreleaser_amd64.deb
  wget https://github.com/goreleaser/nfpm/releases/download/v${NFPM_VERSION}/nfpm_amd64.deb
  sudo dpkg -i nfpm_amd64.deb
  npm i codeclimate-test-reporter

script: |
  dep check
  dep ensure -v -vendor-only
  go test -race -coverprofile=coverage.out -covermode=atomic .
  npx codeclimate-test-reporter < coverage.out

jobs:
  include:
  - stage: golangci-lint
    go: 1.10.x
    if: type = pull_request
    script: |
      dep ensure -v -vendor-only
      golangci-lint run .
  - stage: goreleaser
    go: 1.10.x
    if: type = push
    script: |
      dep check
      dep ensure -v -vendor-only
      cd cmd/cs
      dep check
      dep ensure -v -vendor-only
      goreleaser --snapshot --skip-sign
