language: go

dist: trusty

go:
- 1.8
- 1.9
- "1.10"
- tip

env:
  - DEP_VERSION=0.4.1

cache: apt

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - npm i -g codeclimate-test-reporter
  - curl -sL https://git.io/goreleaser | head -n -2 | bash
  - tar -xf /tmp/goreleaser.tar.gz -C $GOPATH/bin/

jobs:
  include:
  - stage: test
    script: |
      dep ensure
      go test -race .
  - stage: coverage
    script: |
      dep ensure
      go test -coverprofile=coverage.out -covermode=atomic .
      codeclimate-test-reporter < coverage.out
  - stage: goreleaser
    script: |
      dep ensure
      cd cmd/cs
      dep ensure
      cd ../..
      goreleaser --snapshot
      
