language: go

dist: trusty

go:
- 1.8
- 1.9
- tip

cache: apt

before_install:
  - go get -u github.com/golang/lint/golint
  - go get -u github.com/mattn/goveralls

script:
  - test `gofmt -s -d . | tee -a /dev/fd/2 | wc -l` -eq 0
  - test `bin/golint . | tee -a /dev/fd/2 | wc -l` -eq 0
  - go tool vet .
  - go test -v -race -covermode=atomic -coverprofile=coverage.out .
  - goveralls -coverprofile=coverage.out -service=travis-ci
