language: go

dist: trusty

go:
- 1.8
- 1.9
- "1.10"
- tip

env:
  - DEP_VERSION=0.4.1

cache: apt

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - npm i -g codeclimate-test-reporter

jobs:
  include:
  - stage: test
    script: |
      dep ensure
      go test -race .
  - stage: coverage
    script: |
      dep ensure
      go test -coverprofile=coverage.out -covermode=atomic .
      codeclimate-test-reporter < coverage.out
  - stage: goreleaser
    script: |
      go get -d github.com/goreleaser/goreleaser
      cd $GOPATH/src/github.com/goreleaser/goreleaser
      dep ensure -vendor-only
      make build
      go install
      cd $GOPATH/src/github.com/exoscale/egoscale
      dep ensure
      cd cmd/exo
      dep ensure
      goreleaser --snapshot
  - stage: cmd-linux
    script: |
      dep ensure
      cd cmd/cs
      dep ensure
      GOOS=linux go build -ldflags "-s" .
  - stage: cmd-windows
    script: |
      dep ensure
      cd cmd/cs
      dep ensure
      GOOS=windows go build -ldflags "-s" .
  - stage: cmd-darwin
    script: |
      dep ensure
      cd cmd/cs
      dep ensure
      GOOS=darwin go build -ldflags "-s" .
