// Code generated by v3/generator; DO NOT EDIT.
package recorder

import (
	"context"


	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
v3 "github.com/exoscale/egoscale/v3"
)

type LoadBalancersAPI struct {
    Recordee *v3.LoadBalancersAPI
}


func (a *LoadBalancersAPI) List(ctx context.Context) ([]v3.LoadBalancer, error) {
    return a.Recordee.List(ctx, )
}

func (a *LoadBalancersAPI) Get(ctx context.Context, id openapi_types.UUID) (*v3.LoadBalancer, error) {
    return a.Recordee.Get(ctx, id)
}

func (a *LoadBalancersAPI) Create(ctx context.Context, body v3.CreateLoadBalancerJSONRequestBody) (*v3.Operation, error) {
    return a.Recordee.Create(ctx, body)
}

func (a *LoadBalancersAPI) Update(ctx context.Context, id openapi_types.UUID, body v3.UpdateLoadBalancerJSONRequestBody) (*v3.Operation, error) {
    return a.Recordee.Update(ctx, id, body)
}

func (a *LoadBalancersAPI) Delete(ctx context.Context, id openapi_types.UUID) (*v3.Operation, error) {
    return a.Recordee.Delete(ctx, id)
}

func (a *LoadBalancersAPI) GetService(ctx context.Context, id openapi_types.UUID, serviceId openapi_types.UUID) (*v3.LoadBalancerService, error) {
    return a.Recordee.GetService(ctx, id, serviceId)
}

func (a *LoadBalancersAPI) AddService(ctx context.Context, id openapi_types.UUID, body v3.AddServiceToLoadBalancerJSONRequestBody) (*v3.Operation, error) {
    return a.Recordee.AddService(ctx, id, body)
}

func (a *LoadBalancersAPI) UpdateService(ctx context.Context, id openapi_types.UUID, serviceId openapi_types.UUID, body v3.UpdateLoadBalancerServiceJSONRequestBody) (*v3.Operation, error) {
    return a.Recordee.UpdateService(ctx, id, serviceId, body)
}

func (a *LoadBalancersAPI) DeleteService(ctx context.Context, id openapi_types.UUID, serviceId openapi_types.UUID) (*v3.Operation, error) {
    return a.Recordee.DeleteService(ctx, id, serviceId)
}

