// Code generated by v3/generator; DO NOT EDIT.
package recorder

import (
	"context"

v3 "github.com/exoscale/egoscale/v3"
)

type OrgQuotasAPI struct {
    Recordee *v3.OrgQuotasAPI
}


func (a *OrgQuotasAPI) List(ctx context.Context) ([]v3.Quota, error) {
    req := argsToMap()

    resp, err := a.Recordee.List(ctx, )

    writeErr := RecordCall("OrgQuotasAPI.List", req, resp, err)
    if writeErr != nil {
       panic(writeErr)
    }

    return resp, err
}

func (a *OrgQuotasAPI) Get(ctx context.Context, entity string) (*v3.Quota, error) {
    req := argsToMap(entity)

    resp, err := a.Recordee.Get(ctx, entity)

    writeErr := RecordCall("OrgQuotasAPI.Get", req, resp, err)
    if writeErr != nil {
       panic(writeErr)
    }

    return resp, err
}

