// Code generated by v3/generator; DO NOT EDIT.
package recorder

import (
	"context"

v3 "github.com/exoscale/egoscale/v3"
)

type AccessKeyAPI struct {
    Recordee *v3.AccessKeyAPI
}


func (a *AccessKeyAPI) List(ctx context.Context) ([]v3.AccessKey, error) {
    return a.Recordee.List(ctx, )
}

func (a *AccessKeyAPI) ListKnownOperations(ctx context.Context) ([]v3.AccessKeyOperation, error) {
    return a.Recordee.ListKnownOperations(ctx, )
}

func (a *AccessKeyAPI) ListOperations(ctx context.Context) ([]v3.AccessKeyOperation, error) {
    return a.Recordee.ListOperations(ctx, )
}

func (a *AccessKeyAPI) Get(ctx context.Context, key string) (*v3.AccessKey, error) {
    return a.Recordee.Get(ctx, key)
}

func (a *AccessKeyAPI) Create(ctx context.Context, body v3.CreateAccessKeyJSONRequestBody) (*v3.AccessKey, error) {
    return a.Recordee.Create(ctx, body)
}

func (a *AccessKeyAPI) Revoke(ctx context.Context, key string) (*v3.Operation, error) {
    return a.Recordee.Revoke(ctx, key)
}

