// Code generated by v3/generator; DO NOT EDIT.
package recorder

import (
	"context"


	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
v3 "github.com/exoscale/egoscale/v3"
)

type RolesAPI struct {
    Recordee *v3.RolesAPI
}


func (a *RolesAPI) List(ctx context.Context) ([]v3.IamRole, error) {
    return a.Recordee.List(ctx, )
}

func (a *RolesAPI) Get(ctx context.Context, id openapi_types.UUID) (*v3.IamRole, error) {
    return a.Recordee.Get(ctx, id)
}

func (a *RolesAPI) Create(ctx context.Context, body v3.CreateIamRoleJSONRequestBody) (*v3.Operation, error) {
    return a.Recordee.Create(ctx, body)
}

func (a *RolesAPI) Delete(ctx context.Context, id openapi_types.UUID) (*v3.Operation, error) {
    return a.Recordee.Delete(ctx, id)
}

func (a *RolesAPI) Update(ctx context.Context, id openapi_types.UUID, body v3.UpdateIamRoleJSONRequestBody) (*v3.Operation, error) {
    return a.Recordee.Update(ctx, id, body)
}

func (a *RolesAPI) UpdatePolicy(ctx context.Context, id openapi_types.UUID, body v3.UpdateIamRolePolicyJSONRequestBody) (*v3.Operation, error) {
    return a.Recordee.UpdatePolicy(ctx, id, body)
}

