// Code generated by v3/generator; DO NOT EDIT.
package recorder

import (
	"context"

v3 "github.com/exoscale/egoscale/v3"
)

type OrgPolicyAPI struct {
    Recordee *v3.OrgPolicyAPI
}


func (a *OrgPolicyAPI) Get(ctx context.Context) (*v3.IamPolicy, error) {
    return a.Recordee.Get(ctx, )
}

func (a *OrgPolicyAPI) Update(ctx context.Context, body v3.UpdateIamOrganizationPolicyJSONRequestBody) (*v3.Operation, error) {
    return a.Recordee.Update(ctx, body)
}

