// Code generated by v3/generator; DO NOT EDIT.
package recorder

import (
	"context"

v3 "github.com/exoscale/egoscale/v3"
)

type OrgPolicyAPI struct {
    Recordee *v3.OrgPolicyAPI
}


func (a *OrgPolicyAPI) Get(ctx context.Context) (*v3.IamPolicy, error) {
    req := argsToMap()

    resp, err := a.Recordee.Get(ctx, )
    respMap := argsToMap(resp, err)

    writeErr := WriteTestdata("OrgPolicyAPI.Get", req, respMap, 0)
    if writeErr != nil {
       panic(writeErr)
    }

    return resp, err
}

func (a *OrgPolicyAPI) Update(ctx context.Context, body v3.UpdateIamOrganizationPolicyJSONRequestBody) (*v3.Operation, error) {
    req := argsToMap(body)

    resp, err := a.Recordee.Update(ctx, body)
    respMap := argsToMap(resp, err)

    writeErr := WriteTestdata("OrgPolicyAPI.Update", req, respMap, 0)
    if writeErr != nil {
       panic(writeErr)
    }

    return resp, err
}

