// Code generated by v3/generator; DO NOT EDIT.
package v3

import (
    "github.com/exoscale/egoscale/v3/api/dns"
    "github.com/exoscale/egoscale/v3/api/compute"
    "github.com/exoscale/egoscale/v3/api/dbaas"
    "github.com/exoscale/egoscale/v3/api/iam"
    "github.com/exoscale/egoscale/v3/api/global"
)



// DNS provides access to DNS resources on Exoscale platform.
func (c *Client) DNS() *dns.DNS {
	return dns.NewDNS(c.oapiClient)
}

// Compute provides access to Compute resources on Exoscale platform.
func (c *Client) Compute() *compute.Compute {
	return compute.NewCompute(c.oapiClient)
}

// DBaaS provides access to DBaaS resources on Exoscale platform.
func (c *Client) DBaaS() *dbaas.DBaaS {
	return dbaas.NewDBaaS(c.oapiClient)
}

// IAM provides access to IAM resources on Exoscale platform.
func (c *Client) IAM() *iam.IAM {
	return iam.NewIAM(c.oapiClient)
}

// Global provides access to Global resources on Exoscale platform.
func (c *Client) Global() *global.Global {
	return global.NewGlobal(c.oapiClient)
}

