// Code generated by v3/generator; DO NOT EDIT.
package v3

import (
	"context"


	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

type PrivateNetworksAPI struct {
	client *Client
}


func (a *PrivateNetworksAPI) List(ctx context.Context) ([]PrivateNetwork, error) {
	req, err := newListPrivateNetworksRequest(a.client.server)
	if err != nil {
		return nil, err
	}

	req = req.WithContext(ctx)

	for _, e := range a.client.reqEditors {
		err = e(ctx, req)
		if err != nil {
			return nil, err
		}
	}

	r, err := a.client.httpClient.Do(req)
	if err != nil {
		return nil, err
	}

	resp, err := parseListPrivateNetworksResponse(r)
	if err != nil {
		return nil, err
	}

	err = ParseResponseError(resp.StatusCode(), resp.Body)
	if err != nil {
		return nil, err
	}

	return *resp.JSON200.PrivateNetworks, nil
}

func (a *PrivateNetworksAPI) Get(ctx context.Context, id openapi_types.UUID) (*PrivateNetwork, error) {
	req, err := newGetPrivateNetworkRequest(a.client.server, id)
	if err != nil {
		return nil, err
	}

	req = req.WithContext(ctx)

	for _, e := range a.client.reqEditors {
		err = e(ctx, req)
		if err != nil {
			return nil, err
		}
	}

	r, err := a.client.httpClient.Do(req)
	if err != nil {
		return nil, err
	}

	resp, err := parseGetPrivateNetworkResponse(r)
	if err != nil {
		return nil, err
	}

	err = ParseResponseError(resp.StatusCode(), resp.Body)
	if err != nil {
		return nil, err
	}

	return resp.JSON200, nil
}

func (a *PrivateNetworksAPI) Create(ctx context.Context, body CreatePrivateNetworkJSONRequestBody) (*Operation, error) {
	req, err := newCreatePrivateNetworkRequest(a.client.server, body)
	if err != nil {
		return nil, err
	}

	req = req.WithContext(ctx)

	for _, e := range a.client.reqEditors {
		err = e(ctx, req)
		if err != nil {
			return nil, err
		}
	}

	r, err := a.client.httpClient.Do(req)
	if err != nil {
		return nil, err
	}

	resp, err := parseCreatePrivateNetworkResponse(r)
	if err != nil {
		return nil, err
	}

	err = ParseResponseError(resp.StatusCode(), resp.Body)
	if err != nil {
		return nil, err
	}

	return resp.JSON200, nil
}

func (a *PrivateNetworksAPI) Update(ctx context.Context, id openapi_types.UUID, body UpdatePrivateNetworkJSONRequestBody) (*Operation, error) {
	req, err := newUpdatePrivateNetworkRequest(a.client.server, id, body)
	if err != nil {
		return nil, err
	}

	req = req.WithContext(ctx)

	for _, e := range a.client.reqEditors {
		err = e(ctx, req)
		if err != nil {
			return nil, err
		}
	}

	r, err := a.client.httpClient.Do(req)
	if err != nil {
		return nil, err
	}

	resp, err := parseUpdatePrivateNetworkResponse(r)
	if err != nil {
		return nil, err
	}

	err = ParseResponseError(resp.StatusCode(), resp.Body)
	if err != nil {
		return nil, err
	}

	return resp.JSON200, nil
}

func (a *PrivateNetworksAPI) Delete(ctx context.Context, id openapi_types.UUID) (*Operation, error) {
	req, err := newDeletePrivateNetworkRequest(a.client.server, id)
	if err != nil {
		return nil, err
	}

	req = req.WithContext(ctx)

	for _, e := range a.client.reqEditors {
		err = e(ctx, req)
		if err != nil {
			return nil, err
		}
	}

	r, err := a.client.httpClient.Do(req)
	if err != nil {
		return nil, err
	}

	resp, err := parseDeletePrivateNetworkResponse(r)
	if err != nil {
		return nil, err
	}

	err = ParseResponseError(resp.StatusCode(), resp.Body)
	if err != nil {
		return nil, err
	}

	return resp.JSON200, nil
}

