// Code generated by v3/generator; DO NOT EDIT.
package v3

import (
	"context"

)

type IntegrationsAPI struct {
	client *Client
}


func (a *IntegrationsAPI) ListSettings(ctx context.Context, integrationType string, sourceType string, destType string) (*DBaaSIntegrationSettings, error) {
	req, err := newListDbaasIntegrationSettingsRequest(a.client.server, integrationType, sourceType, destType)
	if err != nil {
		return nil, err
	}

	req = req.WithContext(ctx)

	for _, e := range a.client.reqEditors {
		err = e(ctx, req)
		if err != nil {
			return nil, err
		}
	}

	r, err := a.client.httpClient.Do(req)
	if err != nil {
		return nil, err
	}

	resp, err := parseListDbaasIntegrationSettingsResponse(r)
	if err != nil {
		return nil, err
	}

	err = ParseResponseError(resp.StatusCode(), resp.Body)
	if err != nil {
		return nil, err
	}

	return fromListDbaasIntegrationSettingsResponse(resp), nil
}

