// Code generated by v3/generator; DO NOT EDIT.
package replayer

import (
	"context"


	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
v3 "github.com/exoscale/egoscale/v3"
)

type InstanceTypesAPI struct {}


func (a *InstanceTypesAPI) List(ctx context.Context) ([]v3.InstanceType, error) {
    resp := InitializeReturnType[[]v3.InstanceType](a.List)

    var returnErr error
    writeErr := GetTestCall(&resp, &returnErr)
    if writeErr != nil {
       panic(writeErr)
    }

    return resp, returnErr
}

func (a *InstanceTypesAPI) Get(ctx context.Context, id openapi_types.UUID) (*v3.InstanceType, error) {
    resp := InitializeReturnType[*v3.InstanceType](a.Get)

    var returnErr error
    writeErr := GetTestCall(&resp, &returnErr)
    if writeErr != nil {
       panic(writeErr)
    }

    return resp, returnErr
}

