// Code generated by v3/generator; DO NOT EDIT.
package replayer

import (
	"context"

v3 "github.com/exoscale/egoscale/v3"
)

type OrgQuotasAPI struct {
     Replayer *Replayer
}


func (a *OrgQuotasAPI) List(ctx context.Context) ([]v3.Quota, error) {
    resp := InitializeReturnType[[]v3.Quota](a.List)

    var returnErr error
    writeErr := a.Replayer.GetTestCall(&resp, &returnErr)
    if writeErr != nil {
       panic(writeErr)
    }

    return resp, returnErr
}

func (a *OrgQuotasAPI) Get(ctx context.Context, entity string) (*v3.Quota, error) {
    resp := InitializeReturnType[*v3.Quota](a.Get)

    var returnErr error
    writeErr := a.Replayer.GetTestCall(&resp, &returnErr)
    if writeErr != nil {
       panic(writeErr)
    }

    return resp, returnErr
}

