// Code generated by v3/generator; DO NOT EDIT.
package replayer

import (
	"context"

v3 "github.com/exoscale/egoscale/v3"
	"github.com/exoscale/egoscale/v3/testing/recorder"
)

type OrgQuotasAPI struct {
    Replayer *Replayer

    ListHook func(ctx context.Context) error

    GetHook func(ctx context.Context, entity string) error

}


func (a *OrgQuotasAPI) List(ctx context.Context) ([]v3.Quota, error) {
    resp := InitializeReturnType[[]v3.Quota](a.List)

    expectedArgs := make(recorder.CallParameters)
    var returnErr error
    err := a.Replayer.GetTestCall(&resp, &expectedArgs, &returnErr)
    if err != nil {
        panic(err)
    }

    if a.ListHook == nil {
        
    } else {
        if err := a.ListHook(ctx); err != nil {
            panic(err)
        }
    }

    return resp, returnErr
}

func (a *OrgQuotasAPI) Get(ctx context.Context, entity string) (*v3.Quota, error) {
    resp := InitializeReturnType[*v3.Quota](a.Get)

    expectedArgs := make(recorder.CallParameters)
    var returnErr error
    err := a.Replayer.GetTestCall(&resp, &expectedArgs, &returnErr)
    if err != nil {
        panic(err)
    }

    if a.GetHook == nil {
        
             a.Replayer.AssertArgs(expectedArgs, entity)
        
    } else {
        if err := a.GetHook(ctx, entity); err != nil {
            panic(err)
        }
    }

    return resp, returnErr
}

