// Code generated by v3/generator; DO NOT EDIT.
package recorder

import (
	"context"

v3 "github.com/exoscale/egoscale/v3"
)

type IntegrationsAPI struct {
    Recordee *v3.IntegrationsAPI
}


func (a *IntegrationsAPI) ListSettings(ctx context.Context, integrationType string, sourceType string, destType string) (*v3.DBaaSIntegrationSettings, error) {
    req := argsToMap(integrationType, sourceType, destType)

    resp, err := a.Recordee.ListSettings(ctx, integrationType, sourceType, destType)

    writeErr := RecordCall("IntegrationsAPI.ListSettings", req, resp, err)
    if writeErr != nil {
       panic(writeErr)
    }

    return resp, err
}

