// Code generated by v3/generator; DO NOT EDIT.
package replayer

import (
	"context"

v3 "github.com/exoscale/egoscale/v3"
)

type SSHKeysAPI struct {}


func (a *SSHKeysAPI) List(ctx context.Context) ([]v3.SshKey, error) {
    resp := InitializeReturnType[[]v3.SshKey](a.List)

    var returnErr *error
    writeErr := GetTestCall(&resp, returnErr)
    if writeErr != nil {
       panic(writeErr)
    }

    if returnErr == nil {
       return resp, nil
    }

    return resp, *returnErr
}

func (a *SSHKeysAPI) Register(ctx context.Context, body v3.RegisterSshKeyJSONRequestBody) (*v3.Operation, error) {
    resp := InitializeReturnType[*v3.Operation](a.Register)

    var returnErr *error
    writeErr := GetTestCall(&resp, returnErr)
    if writeErr != nil {
       panic(writeErr)
    }

    if returnErr == nil {
       return resp, nil
    }

    return resp, *returnErr
}

func (a *SSHKeysAPI) Delete(ctx context.Context, name string) (*v3.Operation, error) {
    resp := InitializeReturnType[*v3.Operation](a.Delete)

    var returnErr *error
    writeErr := GetTestCall(&resp, returnErr)
    if writeErr != nil {
       panic(writeErr)
    }

    if returnErr == nil {
       return resp, nil
    }

    return resp, *returnErr
}

func (a *SSHKeysAPI) Get(ctx context.Context, name string) (*v3.SshKey, error) {
    resp := InitializeReturnType[*v3.SshKey](a.Get)

    var returnErr *error
    writeErr := GetTestCall(&resp, returnErr)
    if writeErr != nil {
       panic(writeErr)
    }

    if returnErr == nil {
       return resp, nil
    }

    return resp, *returnErr
}

