// Code generated by v3/generator; DO NOT EDIT.
package replayer

import (
	"context"

v3 "github.com/exoscale/egoscale/v3"
)

type OrgPolicyAPI struct {}


func (a *OrgPolicyAPI) Get(ctx context.Context) (*v3.IamPolicy, error) {
    resp := InitializeReturnType[*v3.IamPolicy](a.Get)

    var returnErr error
    writeErr := GetTestCall(&resp, &returnErr)
    if writeErr != nil {
       panic(writeErr)
    }

    return resp, returnErr
}

func (a *OrgPolicyAPI) Update(ctx context.Context, body v3.UpdateIamOrganizationPolicyJSONRequestBody) (*v3.Operation, error) {
    resp := InitializeReturnType[*v3.Operation](a.Update)

    var returnErr error
    writeErr := GetTestCall(&resp, &returnErr)
    if writeErr != nil {
       panic(writeErr)
    }

    return resp, returnErr
}

