name: build-public-tooling

on:
  push

jobs:
  build_public_tooling:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        repo:
          - exoscale-csi-driver

    steps:
    - name: Build ${{ matrix.repo }}
      id: build
      run: |
        git clone git@github.com:exoscale/${{ matrix.repo }}
        go get github.com/exoscale/egoscale/v3@${{ github.sha }}
        go mod vendor
        make build
