name: CI

on: [push]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.15'
    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.32
    - name: Tests
      run: |
        go test -race -v ./...
