name: CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: lint
      uses: golangci/golangci-lint-action@v1
      with:
        version: v1.27
    - name: tests
      run: |
        export PATH=$(go env GOPATH)/bin:$PATH
        go test -v -race ./...
