name: CI

on: [push]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.15.0'
    - name: Lint
      uses: golangci/golangci-lint-action@v1
      with:
        version: v1.30
    - name: Tests
      run: |
        go test -v ./...
