name: CI

on:
  push:
    branches:
    - '**'
    paths-ignore:
    - '**.md'
    - 'version/*'
    tags-ignore:
    - 'v**' # Don't run CI tests on release tags

jobs:
  CI:
    runs-on: ubuntu-latest
    env:
      GOLANGCI_LINT_CONFIG: ".golangci.yml"
    steps:
      - uses: actions/checkout@v3
      - run: git submodule update --init --recursive go.mk
      - uses: ./go.mk/.github/actions/setup

      - uses: ./go.mk/.github/actions/pre-check

      - run: make test-verbose
