name: CI

on:
  pull_request:
  push:
    branches:
    - '**'
    paths-ignore:
    - '**.md'
    - 'version/*'
    tags-ignore:
    - 'v**' # Don't run CI tests on release tags

jobs:
  CI:
    runs-on: ubuntu-latest
    env:
      GOLANGCI_LINT_CONFIG: ".golangci.yml"
    steps:
      - uses: actions/checkout@v4
      - run: make go.mk
      - uses: ./go.mk/.github/actions/setup

      - uses: ./go.mk/.github/actions/pre-check

      - run: make test-verbose

      - name: Check for changes
        id: check_changes
        run: |
          cd v3/generator/
          go generate
          go mod tidy
          cd ..
          # The git adds are used to fix EOL problem:
          # warning: in the working copy of 'v3/generator/vendor/github.com/vmware-labs/yaml-jsonpath/NOTICE', CRLF will be replaced by LF the next time Git touches it
          # https://github.com/vmware-labs/yaml-jsonpath/pull/59
          git add generator/vendor/github.com/vmware-labs/yaml-jsonpath/LICENSE
          git add v3/generator/vendor/github.com/vmware-labs/yaml-jsonpath/NOTICE
          git diff --exit-code
